---
driver:
  name: vagrant
    memory: 2048
    cpus: 1

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[db2::default]
      - recipe[db2::installfp]
      - recipe[db2::instance]
      - recipe[db2::createdb]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
