name             'db2'
maintainer       'Ed Overton'
maintainer_email 'bogus@gmail.com'
license          'Apache-2.0'
description      'Installs/Configures IBM DB2 Enterprise Server version 10.5.9'
version          '1.1'
chef_version '>= 13.0'
supports 'redhat'
supports 'centos'

issues_url 'https://github.com/emo3/db2/issues'
source_url 'https://github.com/emo3/db2'
